jaffle_shop:

  target: dev
  outputs: 
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: localhost
      port: 1433
      schema: dbo
      user: SA
      password: fTw68nEsJM
      database: test_db
      threads: 24
      trust_cert: true
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('MSSQL_PROD') }}"
      port: 1433
      schema: dbo
      user: "{{ env_var('MSSQL_USER') }}"
      password: "{{ env_var('MSSQL_LOGIN') }}"
      database: prod_db
      threads: 24
      trust_cert: true

jaffle_shop_duckdb:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      threads: 24
